# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands

# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t reverseproxy ./udagram-reverseproxy
# Do similar for other three images

# Tagging
- docker tag udagram-api-feed zelenokosa/udagram-api-feed:v1
- docker tag udagram-api-user zelenokosa/udagram-api-user:v1
- docker tag udagram-frontend zelenokosa/udagram-frontend:v1
- docker tag reverseproxy zelenokosa/reverseproxy:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push zelenokosa/udagram-api-feed:v1
- docker push zelenokosa/udagram-api-user:v1
- docker push zelenokosa/udagram-frontend:v1
- docker push zelenokosa/reverseproxy:v1