apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  selector:
    matchLabels:
      service: reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: zelenokosa/reverseproxy
        name: reverseproxy
        imagePullPolicy: Always             
        ports:
        - containerPort: 8080
      restartPolicy: Always


